// <auto-generated />
using System;
using MMV.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MMV.Infrastructure.Migrations
{
    [DbContext(typeof(OpticDbContext))]
    [Migration("20260202005050_AddNotifications")]
    partial class AddNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MMV.Domain.Entities.AccessoryDetail", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("AccessoryDetails");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2026, 2, 2, 0, 50, 50, 128, DateTimeKind.Utc).AddTicks(1963));

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialSecurityNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2026, 2, 2, 0, 50, 50, 128, DateTimeKind.Utc).AddTicks(2278));

                    b.HasKey("CustomerId");

                    b.HasIndex("LastName")
                        .HasDatabaseName("idx_customers_lastname");

                    b.HasIndex("Phone")
                        .HasDatabaseName("idx_customers_phone");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MMV.Domain.Entities.GlassDetail", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Diameter")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("GlassType")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Index")
                        .HasPrecision(3, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PowerLimitMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PowerLimitMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("GlassDetails");
                });

            modelBuilder.Entity("MMV.Domain.Entities.GlassPricingTier", b =>
                {
                    b.Property<long>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GlassId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PowerMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PowerMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePriceGrid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalePriceGrid")
                        .HasColumnType("TEXT");

                    b.HasKey("TierId");

                    b.HasIndex("GlassId", "PowerMin", "PowerMax")
                        .HasDatabaseName("idx_glass_pricing_tier_range");

                    b.ToTable("GlassPricingTiers");
                });

            modelBuilder.Entity("MMV.Domain.Entities.GlassSupplement", b =>
                {
                    b.Property<long>("GlassId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SupplementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GlassId", "SupplementId");

                    b.HasIndex("SupplementId");

                    b.ToTable("GlassSupplements");
                });

            modelBuilder.Entity("MMV.Domain.Entities.LensDetail", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BaseCurve")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Diameter")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsColored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LensType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("LensDetails");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("NotificationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("Type");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("MMV.Domain.Entities.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EstimatedDelivery")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2026, 2, 2, 0, 50, 50, 128, DateTimeKind.Utc).AddTicks(8562));

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StaffId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("New");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("REAL");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_orders_customer_id");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_orders_order_number_unique");

                    b.HasIndex("StaffId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_orders_status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MMV.Domain.Entities.OrderItem", b =>
                {
                    b.Property<long>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Addition")
                        .HasColumnType("REAL");

                    b.Property<int?>("Axis")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Cylinder")
                        .HasColumnType("REAL");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrismBase")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PrismValue")
                        .HasColumnType("REAL");

                    b.Property<long?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<double?>("Sphere")
                        .HasColumnType("REAL");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("UsageType")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisualAcuity")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Prescription", b =>
                {
                    b.Property<long>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2026, 2, 2, 0, 50, 50, 128, DateTimeKind.Utc).AddTicks(7322));

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoctorName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("OdAddition")
                        .HasColumnType("REAL");

                    b.Property<int?>("OdAxis")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OdCylinder")
                        .HasColumnType("REAL");

                    b.Property<string>("OdPrismBase")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OdPrismValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("OdSphere")
                        .HasColumnType("REAL");

                    b.Property<string>("OdVisualAcuity")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double?>("OgAddition")
                        .HasColumnType("REAL");

                    b.Property<int?>("OgAxis")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OgCylinder")
                        .HasColumnType("REAL");

                    b.Property<string>("OgPrismBase")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OgPrismValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("OgSphere")
                        .HasColumnType("REAL");

                    b.Property<string>("OgVisualAcuity")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("RecommendedPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("REAL");

                    b.Property<int>("StockAlertThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5);

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<long>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechnicalSpecs")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_products_category_id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("idx_products_reference_unique");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MMV.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_product_categories_name_unique");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Sale", b =>
                {
                    b.Property<long>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Paid");

                    b.Property<DateTime>("SaleDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2026, 2, 2, 0, 50, 50, 129, DateTimeKind.Utc).AddTicks(4136));

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StaffId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("REAL");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SaleDate")
                        .HasDatabaseName("idx_sales_sale_date");

                    b.HasIndex("SaleNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_sales_sale_number_unique");

                    b.HasIndex("StaffId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("MMV.Domain.Entities.SaleItem", b =>
                {
                    b.Property<long>("SaleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("REAL");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("SaleItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("MMV.Domain.Entities.StockMovement", b =>
                {
                    b.Property<long>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2026, 2, 2, 0, 50, 50, 129, DateTimeKind.Utc).AddTicks(9573));

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PerformedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("MovementId");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_stock_movements_product_id");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Supplement", b =>
                {
                    b.Property<long>("SupplementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SupplementPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("SupplementId");

                    b.ToTable("Supplements");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Supplier", b =>
                {
                    b.Property<long>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("MMV.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2026, 2, 2, 0, 50, 50, 124, DateTimeKind.Utc).AddTicks(872));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_users_username_unique");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            CreatedAt = new DateTime(2026, 2, 2, 0, 50, 50, 130, DateTimeKind.Utc).AddTicks(1708),
                            FirstName = "Administrateur",
                            IsActive = true,
                            LastName = "Système",
                            PasswordHash = "$2a$11$dXJ3SW6G7P50eS6xFJwFHeJ/hbtjiZlyCloO/sURR8EZ4/nqXJcOy",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MMV.Domain.Entities.AccessoryDetail", b =>
                {
                    b.HasOne("MMV.Domain.Entities.Product", "Product")
                        .WithOne("AccessoryDetail")
                        .HasForeignKey("MMV.Domain.Entities.AccessoryDetail", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MMV.Domain.Entities.GlassDetail", b =>
                {
                    b.HasOne("MMV.Domain.Entities.Product", "Product")
                        .WithOne("GlassDetail")
                        .HasForeignKey("MMV.Domain.Entities.GlassDetail", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MMV.Domain.Entities.GlassPricingTier", b =>
                {
                    b.HasOne("MMV.Domain.Entities.GlassDetail", "Glass")
                        .WithMany("PricingTiers")
                        .HasForeignKey("GlassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Glass");
                });

            modelBuilder.Entity("MMV.Domain.Entities.GlassSupplement", b =>
                {
                    b.HasOne("MMV.Domain.Entities.GlassDetail", "Glass")
                        .WithMany("GlassSupplements")
                        .HasForeignKey("GlassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMV.Domain.Entities.Supplement", "Supplement")
                        .WithMany("GlassSupplements")
                        .HasForeignKey("SupplementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Glass");

                    b.Navigation("Supplement");
                });

            modelBuilder.Entity("MMV.Domain.Entities.LensDetail", b =>
                {
                    b.HasOne("MMV.Domain.Entities.Product", "Product")
                        .WithOne("LensDetail")
                        .HasForeignKey("MMV.Domain.Entities.LensDetail", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Order", b =>
                {
                    b.HasOne("MMV.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MMV.Domain.Entities.User", "Staff")
                        .WithMany("Orders")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("MMV.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("MMV.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMV.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("MMV.Domain.Entities.Customer", "Customer")
                        .WithMany("Prescriptions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Product", b =>
                {
                    b.HasOne("MMV.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MMV.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Sale", b =>
                {
                    b.HasOne("MMV.Domain.Entities.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MMV.Domain.Entities.User", "Staff")
                        .WithMany("Sales")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("MMV.Domain.Entities.SaleItem", b =>
                {
                    b.HasOne("MMV.Domain.Entities.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MMV.Domain.Entities.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("MMV.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("MMV.Domain.Entities.User", "PerformedByUser")
                        .WithMany("StockMovements")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MMV.Domain.Entities.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedByUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Prescriptions");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("MMV.Domain.Entities.GlassDetail", b =>
                {
                    b.Navigation("GlassSupplements");

                    b.Navigation("PricingTiers");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Product", b =>
                {
                    b.Navigation("AccessoryDetail");

                    b.Navigation("GlassDetail");

                    b.Navigation("LensDetail");

                    b.Navigation("OrderItems");

                    b.Navigation("SaleItems");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("MMV.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Supplement", b =>
                {
                    b.Navigation("GlassSupplements");
                });

            modelBuilder.Entity("MMV.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MMV.Domain.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Sales");

                    b.Navigation("StockMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
