using System.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using MMV.Domain.Entities;
using MMV.Domain.Exceptions;
using MMV.Infrastructure.Data;
using MMV.Infrastructure.Persistence;
using MMV.Infrastructure.Repositories;
using MMV.P4.ProviderComparison.Support;
using Xunit;

namespace MMV.P4.ProviderComparison;

/// <summary>
/// E21 (P4-4B0) — MESURE du comportement TRANSACTIONNEL PostgreSQL.
///
/// <para>
/// P4-4A1 a mis <c>PersistenceErrorMapper</c> PostgreSQL en production. Cette expérimentation
/// mesure ce qui l'entoure : la FRONTIÈRE transactionnelle. Elle ne corrige rien et ne modifie
/// aucun fichier de <c>src/**</c> ni de <c>tests/**</c>.
/// </para>
///
/// <para>
/// PORTÉE DE LA PREUVE — trois niveaux strictement distincts, jamais confondus dans le rapport :
/// <list type="bullet">
///   <item><b>EXECUTED_SPIKE</b> : SQL brut du harness (B0.1). Prouve le SERVEUR, pas MMV.</item>
///   <item><b>PRODUCTION_CODE_EXECUTED</b> : le VRAI <see cref="EfTransactionRunner"/>, le VRAI
///     <see cref="OpticDbContext"/>, le VRAI <see cref="PersistenceErrorMapper"/>, le VRAI
///     <see cref="UnitOfWork"/> et le VRAI <see cref="SupplierRepository"/> sont instanciés et
///     exécutés tels quels sur PostgreSQL.</item>
///   <item><b>GENERIC_EF_EVIDENCE</b> : mécanique EF Core mesurée sur une table du HARNESS.</item>
/// </list>
/// </para>
///
/// <para>
/// AUCUN SCHÉMA DE PRODUCTION N'EST REVENDIQUÉ. <c>EnsureCreated()</c> et <c>Migrate()</c> ne sont
/// JAMAIS appelés sur le modèle de production : il n'est pas encore portable (index filtrés
/// <c>"IsCurrent" = 1</c>, mapping monétaire <c>REAL</c>, <c>DateTime</c> — tout cela relève de
/// P4-5). Les tables utilisées ici sont créées à la main par SQL brut, dans une base JETABLE, et
/// sont des INSTRUMENTS DE MESURE : la contrainte d'unicité posée sur <c>"Suppliers"."Name"</c>
/// n'existe PAS dans le modèle MMV et ne préjuge d'aucune migration.
/// </para>
///
/// <para>
/// RÈGLE reconduite d'E19/E20 : aucune décision ne s'appuie sur <c>Exception.Message</c>. Seuls des
/// tests de TYPE et des propriétés STRUCTURÉES (<c>SqlState</c>,
/// <c>PersistenceException.Category</c>, <c>CancellationToken.IsCancellationRequested</c>) sont
/// utilisés. Aucun secret, aucune chaîne de connexion n'est journalisé.
/// </para>
///
/// <para>
/// AUCUN RÉGLAGE DE PRODUCTION N'EST INTRODUIT : ni réessai, ni <c>EnableRetryOnFailure</c>, ni
/// <c>lock_timeout</c>, ni <c>statement_timeout</c>, ni <c>CommandTimeout</c>, ni
/// <c>TransactionScope</c>, ni changement de niveau d'isolation.
/// </para>
/// </summary>
[Collection(SpikeSerialCollection.Name)]
public class E21_PostgreSqlTransactionBehaviorTests
{
    private const string Experiment = "E21-postgresql-transaction-behavior";

    private const ProviderKind Provider = ProviderKind.Postgres;

    private const string Name = nameof(ProviderKind.Postgres);

    /// <summary>Table de sonde du harness. Jamais une table MMV.</summary>
    private const string CreateProbeTable =
        "CREATE TABLE p4_tx_probe (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
        "code text NOT NULL CONSTRAINT ux_p4_tx_probe_code UNIQUE);";

    // ==================================================================================
    // B0.1 — CONTRÔLE POSITIF : le laboratoire détecte-t-il réellement 25P02 ?
    // ==================================================================================

    /// <summary>
    /// B0.1 — Sans ce contrôle, un test qui « ne voit pas de 25P02 » ne prouverait rien : il pourrait
    /// simplement être aveugle. On provoque donc délibérément l'état que la production doit éviter.
    /// Niveau : EXECUTED_SPIKE (SQL brut, aucun code MMV).
    /// </summary>
    [SkippableFact]
    public async Task B01_aborted_transaction_really_yields_25P02()
    {
        Skip.IfNot(SpikeEnvironment.IsConfigured(Provider), SpikeEnvironment.SkipReason(Provider));

        await using var database = await SpikeDatabase.CreateAsync(Provider, "e21b01");
        SpikeLog.Section(Experiment, Name, "B0.1 — CONTROLE POSITIF 25P02 (SQL brut, aucun code MMV)");

        await ExecuteOutsideTransactionAsync(database, CreateProbeTable);

        await using var connection = await database.OpenRawAsync();
        await using var transaction = await connection.BeginTransactionAsync();

        // 1er INSERT : accepté.
        await ExecuteAsync(connection, transaction, "INSERT INTO p4_tx_probe (code) VALUES ('A');");

        // 2e INSERT : violation d'unicité attendue.
        var duplicate = await CaptureAsync(() =>
            ExecuteAsync(connection, transaction, "INSERT INTO p4_tx_probe (code) VALUES ('A');"));

        Assert.NotNull(duplicate);
        var duplicateShape = ExceptionShape.Capture(duplicate!);
        Assert.True(duplicateShape.HasPostgresException, "B0.1 : PostgresException attendue sur le doublon.");
        Assert.Equal("23505", duplicateShape.SqlState);
        SpikeLog.Write(Experiment, Name, $"B0.1 doublon | {duplicateShape.ToEvidenceLine()}");

        // SANS rollback : toute commande suivante doit être refusée. C'est LE contrôle positif.
        var afterFailure = await CaptureAsync(() =>
            ExecuteAsync(connection, transaction, "SELECT count(*) FROM p4_tx_probe;"));

        Assert.NotNull(afterFailure);
        var abortedShape = ExceptionShape.Capture(afterFailure!);
        Assert.Equal("25P02", abortedShape.SqlState);
        SpikeLog.Write(Experiment, Name, $"B0.1 commande apres erreur SANS rollback | {abortedShape.ToEvidenceLine()}");

        // Après ROLLBACK, la même commande doit repasser.
        await transaction.RollbackAsync();

        await using (var afterRollback = connection.CreateCommand())
        {
            afterRollback.CommandText = "SELECT count(*) FROM p4_tx_probe;";
            var count = Convert.ToInt64(await afterRollback.ExecuteScalarAsync());
            Assert.Equal(0L, count); // aucune ligne 'A' persistée
            SpikeLog.Write(Experiment, Name,
                $"B0.1 apres ROLLBACK | commande acceptee=OUI | lignes persistees={count}");
        }

        SpikeLog.Write(Experiment, Name, "B0.1 = CONTROLE POSITIF VALIDE (le laboratoire voit reellement 25P02).");
    }

    // ==================================================================================
    // B0.2 / B0.4 — LE VRAI EfTransactionRunner SUR POSTGRESQL
    // ==================================================================================

    /// <summary>
    /// B0.2 — Le VRAI <see cref="EfTransactionRunner"/> de production, construit sur le VRAI
    /// <see cref="OpticDbContext"/> configuré Npgsql, exécuté tel quel.
    ///
    /// <para>
    /// Le schéma de production n'est PAS créé : le callback n'utilise que la table de sonde du
    /// harness. C'est suffisant et volontaire — le runner ne touche jamais au modèle, il n'utilise
    /// que <c>Database.CurrentTransaction</c>, <c>BeginTransactionAsync</c>, <c>CommitAsync</c> et
    /// <c>RollbackAsync</c>. La frontière transactionnelle mesurée est donc EXACTEMENT celle de la
    /// production.
    /// </para>
    ///
    /// <para>B0.4 est mesuré dans le même test par un intercepteur du HARNESS.</para>
    /// </summary>
    [SkippableFact]
    public async Task B02_real_transaction_runner_rolls_back_and_maps_unique_violation()
    {
        Skip.IfNot(SpikeEnvironment.IsConfigured(Provider), SpikeEnvironment.SkipReason(Provider));

        await using var database = await SpikeDatabase.CreateAsync(Provider, "e21b02");
        SpikeLog.Section(Experiment, Name, "B0.2 — VRAI EfTransactionRunner de production sur PostgreSQL");

        await ExecuteOutsideTransactionAsync(database, CreateProbeTable);

        var recorder = new CommandRecorder();
        await using var context = CreateProductionContext(database, recorder);

        // *** CODE DE PRODUCTION, INSTANCIÉ TEL QUEL ***
        var runner = new EfTransactionRunner(context);

        recorder.Start("callback");

        var thrown = await CaptureAsync(() => runner.RunAsync(async ct =>
        {
            await context.Database.ExecuteSqlRawAsync("INSERT INTO p4_tx_probe (code) VALUES ('B');", ct);
            await context.Database.ExecuteSqlRawAsync("INSERT INTO p4_tx_probe (code) VALUES ('B');", ct);
        }, CancellationToken.None));

        recorder.Stop();

        // --- 1) Exception finale reçue par l'appelant -------------------------------------------
        Assert.NotNull(thrown);
        var shape = ExceptionShape.Capture(thrown!);
        SpikeLog.Write(Experiment, Name, $"B0.2 exception sortie du runner | {shape.ToEvidenceLine()}");

        var mapped = Assert.IsType<PersistenceException>(thrown);
        Assert.Equal(PersistenceErrorCategory.UniqueConstraint, mapped.Category);
        Assert.Equal("23505", shape.SqlState);
        Assert.True(shape.HasPostgresException,
            "B0.2 : la PostgresException d'origine doit rester accessible en InnerException.");
        SpikeLog.Write(Experiment, Name,
            $"B0.2 mapping | type={mapped.GetType().FullName} | Category={mapped.Category} " +
            $"| SqlState conserve={shape.SqlState} | contrainte={shape.ConstraintName ?? "(aucune)"}");

        // --- 2) L'écriture #1 a-t-elle été annulée elle aussi ? ----------------------------------
        var remaining = await CountProbeAsync(database, "B");
        Assert.Equal(0L, remaining);
        SpikeLog.Write(Experiment, Name,
            $"B0.2 donnees apres sortie du runner | lignes code='B' persistees={remaining} " +
            "=> INSERT #1 rollbacke avec la transaction.");

        // --- 3) Le MÊME DbContext est-il réutilisable après le rollback ? ------------------------
        Assert.Null(context.Database.CurrentTransaction);

        var reuse = await context.Database
            .SqlQueryRaw<long>("SELECT count(*)::bigint AS \"Value\" FROM p4_tx_probe")
            .SingleAsync();

        Assert.Equal(0L, reuse);
        SpikeLog.Write(Experiment, Name,
            "B0.2 reutilisation du MEME DbContext apres rollback | requete acceptee=OUI (aucun 25P02) " +
            $"| CurrentTransaction=null | lignes={reuse}");

        // --- 4) B0.4 : commandes applicatives exécutées APRÈS l'erreur, dans la transaction ------
        var afterFailure = recorder.CommandsAfterFirstFailure("callback");
        Assert.Empty(afterFailure);
        SpikeLog.Write(Experiment, Name,
            $"B0.4 commandes applicatives APRES l'echec, dans la transaction = {afterFailure.Count} " +
            $"| sequence complete du callback : {recorder.Describe("callback")}");
        SpikeLog.Write(Experiment, Name,
            "B0.4 LIMITE ASSUMEE : BEGIN/COMMIT/ROLLBACK passent par l'API ADO.NET de transaction, " +
            "PAS par DbCommand — un DbCommandInterceptor ne peut pas les voir. Aucune pretention contraire.");
    }

    // ==================================================================================
    // B0.3 — ANNULATION CLIENTE APRÈS UNE ÉCRITURE
    // ==================================================================================

    /// <summary>
    /// B0.3 — Le jeton client est annulé APRÈS une écriture réussie. Le rollback doit malgré tout
    /// aboutir : c'est précisément ce que garantit le <c>CancellationToken.None</c> de
    /// <c>SafeRollbackAsync</c>. Code de production exécuté tel quel.
    /// </summary>
    [SkippableFact]
    public async Task B03_real_transaction_runner_rolls_back_after_client_cancellation()
    {
        Skip.IfNot(SpikeEnvironment.IsConfigured(Provider), SpikeEnvironment.SkipReason(Provider));

        await using var database = await SpikeDatabase.CreateAsync(Provider, "e21b03");
        SpikeLog.Section(Experiment, Name, "B0.3 — Annulation cliente APRES ecriture, via le VRAI runner");

        await ExecuteOutsideTransactionAsync(database, CreateProbeTable);

        await using var context = CreateProductionContext(database, recorder: null);
        var runner = new EfTransactionRunner(context);

        using var cts = new CancellationTokenSource();

        var thrown = await CaptureAsync(() => runner.RunAsync(async ct =>
        {
            await context.Database.ExecuteSqlRawAsync("INSERT INTO p4_tx_probe (code) VALUES ('C');", ct);

            // Le jeton est annulé APRÈS l'écriture : au moment du rollback il est déjà déclenché.
            cts.Cancel();
            throw new OperationCanceledException(cts.Token);
        }, cts.Token));

        Assert.NotNull(thrown);
        var shape = ExceptionShape.Capture(thrown!);
        SpikeLog.Write(Experiment, Name, $"B0.3 exception sortie du runner | {shape.ToEvidenceLine()}");

        // Le comportement d'annulation doit être PRÉSERVÉ : jamais transformé en erreur de persistance.
        Assert.IsNotType<PersistenceException>(thrown);
        Assert.True(shape.HasOperationCanceledException);
        Assert.True(shape.CancellationWasRequested);

        // Malgré le jeton déjà annulé, le rollback a-t-il abouti ?
        var remaining = await CountProbeAsync(database, "C");
        Assert.Equal(0L, remaining);
        SpikeLog.Write(Experiment, Name,
            $"B0.3 donnees apres annulation | lignes code='C' persistees={remaining} " +
            "=> rollback abouti MALGRE un CancellationToken deja annule (SafeRollbackAsync utilise None).");

        Assert.Null(context.Database.CurrentTransaction);
        SpikeLog.Write(Experiment, Name, "B0.3 CurrentTransaction apres sortie = null.");
    }

    // ==================================================================================
    // B0.5 — UNITOFWORK : LE JETON ANNULÉ PEUT-IL MASQUER L'ERREUR / EMPÊCHER LE ROLLBACK ?
    // ==================================================================================

    /// <summary>
    /// B0.5 — <see cref="UnitOfWork"/> n'a AUCUN appelant de production pour
    /// <c>BeginTransactionAsync</c> / <c>CommitAsync</c> / <c>RollbackAsync</c> (vérifié
    /// statiquement). On mesure néanmoins son comportement RÉEL, car son catch relaie le jeton
    /// CLIENT au rollback là où <see cref="EfTransactionRunner"/> utilise
    /// <c>CancellationToken.None</c>.
    ///
    /// <para>
    /// La mesure procède en deux temps : d'abord les PRIMITIVES (que fait Npgsql/EF quand on
    /// commit/rollback avec un jeton déjà annulé ?), puis le COMPOSITE (le vrai
    /// <c>UnitOfWork.CommitAsync</c>).
    /// </para>
    /// </summary>
    [SkippableFact]
    public async Task B05_unit_of_work_rollback_with_already_cancelled_token()
    {
        Skip.IfNot(SpikeEnvironment.IsConfigured(Provider), SpikeEnvironment.SkipReason(Provider));

        await using var database = await SpikeDatabase.CreateAsync(Provider, "e21b05");
        SpikeLog.Section(Experiment, Name, "B0.5 — UnitOfWork : rollback avec jeton client DEJA annule");

        await ExecuteOutsideTransactionAsync(database, CreateProbeTable);

        // --- PRIMITIVE 1 : CommitAsync(jeton annulé) --------------------------------------------
        Exception? commitFailure;
        await using (var context = CreateProductionContext(database, recorder: null))
        {
            await using var transaction = await context.Database.BeginTransactionAsync();
            await context.Database.ExecuteSqlRawAsync("INSERT INTO p4_tx_probe (code) VALUES ('P1');");

            using var cts = new CancellationTokenSource();
            cts.Cancel();

            commitFailure = await CaptureAsync(() => transaction.CommitAsync(cts.Token));
            SpikeLog.Write(Experiment, Name,
                "B0.5 primitive CommitAsync(jeton annule) | " +
                (commitFailure is null
                    ? "AUCUNE exception (le commit a abouti)"
                    : ExceptionShape.Capture(commitFailure).ToEvidenceLine()));
        }

        var persistedP1 = await CountProbeAsync(database, "P1");
        SpikeLog.Write(Experiment, Name,
            $"B0.5 primitive CommitAsync | lignes 'P1' persistees apres liberation du contexte = {persistedP1}");

        // --- PRIMITIVE 2 : RollbackAsync(jeton annulé) sur une transaction vivante ---------------
        // QUESTION DÉCISIVE : si l'appel LÈVE, le rollback a-t-il tout de même eu lieu, ou la
        // transaction reste-t-elle OUVERTE ? On l'observe DEPUIS LA MÊME session, avant toute
        // libération : une transaction encore ouverte voit ses propres écritures non validées.
        Exception? rollbackFailure;
        await using (var context = CreateProductionContext(database, recorder: null))
        {
            await using var transaction = await context.Database.BeginTransactionAsync();
            await context.Database.ExecuteSqlRawAsync("INSERT INTO p4_tx_probe (code) VALUES ('P2');");

            using var cts = new CancellationTokenSource();
            cts.Cancel();

            rollbackFailure = await CaptureAsync(() => transaction.RollbackAsync(cts.Token));
            SpikeLog.Write(Experiment, Name,
                "B0.5 primitive RollbackAsync(jeton annule) | " +
                (rollbackFailure is null
                    ? "AUCUNE exception (le rollback a abouti)"
                    : ExceptionShape.Capture(rollbackFailure).ToEvidenceLine()));

            var transactionStillOpen = context.Database.CurrentTransaction is not null;

            // Lecture DANS la session du test. Si la transaction a bien été annulée, la ligne a
            // disparu ; si elle est encore ouverte, la session voit toujours sa propre écriture.
            var visibleInSession = await CaptureScalarAsync(context,
                "SELECT count(*)::bigint AS \"Value\" FROM p4_tx_probe WHERE code = 'P2'");

            SpikeLog.Write(Experiment, Name,
                $"B0.5 primitive RollbackAsync — ETAT APRES L'EXCEPTION | CurrentTransaction=" +
                $"{(transactionStillOpen ? "ENCORE PRESENTE" : "null")} | lignes 'P2' vues par la MEME session=" +
                $"{visibleInSession?.ToString() ?? "(lecture refusee)"} " +
                "(>0 => le ROLLBACK N'A PAS EU LIEU, la transaction est restee OUVERTE)");

            // Rollback de rattrapage avec CancellationToken.None : exactement ce que fait
            // EfTransactionRunner.SafeRollbackAsync. Doit aboutir.
            var retry = await CaptureAsync(() => transaction.RollbackAsync(CancellationToken.None));
            SpikeLog.Write(Experiment, Name,
                "B0.5 primitive RollbackAsync(CancellationToken.None) de rattrapage | " +
                (retry is null ? "ABOUTI" : ExceptionShape.Capture(retry).ToEvidenceLine()));
        }

        var persistedP2 = await CountProbeAsync(database, "P2");
        SpikeLog.Write(Experiment, Name,
            $"B0.5 primitive RollbackAsync | lignes 'P2' persistees apres liberation du contexte = {persistedP2}");

        // --- COMPOSITE : le VRAI UnitOfWork ------------------------------------------------------
        Exception? unitOfWorkFailure;
        var context3 = CreateProductionContext(database, recorder: null);
        var unitOfWork = new UnitOfWork(context3); // *** CODE DE PRODUCTION ***
        try
        {
            await unitOfWork.BeginTransactionAsync();
            await context3.Database.ExecuteSqlRawAsync("INSERT INTO p4_tx_probe (code) VALUES ('U');");

            using var cts = new CancellationTokenSource();
            cts.Cancel();

            unitOfWorkFailure = await CaptureAsync(() => unitOfWork.CommitAsync(cts.Token));

            // ÉTAT AVANT toute libération : le catch de CommitAsync a-t-il réellement annulé ?
            var stillOpen = context3.Database.CurrentTransaction is not null;
            var visibleInSession = await CaptureScalarAsync(context3,
                "SELECT count(*)::bigint AS \"Value\" FROM p4_tx_probe WHERE code = 'U'");

            SpikeLog.Write(Experiment, Name,
                $"B0.5 composite — ETAT AVANT LIBERATION | CurrentTransaction=" +
                $"{(stillOpen ? "ENCORE PRESENTE" : "null")} | lignes 'U' vues par la MEME session=" +
                $"{visibleInSession?.ToString() ?? "(lecture refusee)"} " +
                "(>0 => le catch de UnitOfWork.CommitAsync n'a PAS annule ; seule la liberation le fera)");
        }
        finally
        {
            await unitOfWork.DisposeAsync();
        }

        var unitOfWorkShape = unitOfWorkFailure is null ? null : ExceptionShape.Capture(unitOfWorkFailure);
        SpikeLog.Write(Experiment, Name,
            "B0.5 composite UnitOfWork.CommitAsync(jeton annule) | " +
            (unitOfWorkShape?.ToEvidenceLine() ?? "AUCUNE exception (le commit a abouti)"));

        var persistedU = await CountProbeAsync(database, "U");
        SpikeLog.Write(Experiment, Name,
            $"B0.5 composite | lignes 'U' persistees apres liberation = {persistedU} " +
            "(0 = aucune ecriture partielle conservee ; >0 = commit effectif malgre le jeton annule)");

        // Faits consignés, pas de correction ici : la décision appartient à P4-4B1.
        SpikeLog.Write(Experiment, Name,
            "B0.5 CONSTAT STATIQUE (invariant) : EfTransactionRunner.SafeRollbackAsync utilise " +
            "CancellationToken.None ; UnitOfWork.RollbackTransactionAsync relaie le jeton CLIENT.");

        // Le test MESURE : il ne doit pas échouer sur un comportement observé. Seule l'absence totale
        // d'observation serait un échec.
        Assert.True(persistedP1 >= 0 && persistedP2 >= 0 && persistedU >= 0,
            "B0.5 : aucune observation n'a pu etre relevee.");
    }

    // ==================================================================================
    // B0.7 — CHANGETRACKER APRÈS SAVECHANGES ÉCHOUÉ, PUIS ExistsFreshAsync
    // ==================================================================================

    /// <summary>
    /// B0.7 — Reproduit la forme EXACTE du chemin <c>CreateProductUseCase</c> /
    /// <c>UpdateProductUseCase</c> : une écriture échoue dans le vrai
    /// <see cref="EfTransactionRunner"/>, la transaction est annulée, puis le catch de production
    /// réinterroge la base avec <c>ExistsFreshAsync</c> — SUR LE MÊME <see cref="OpticDbContext"/>.
    ///
    /// <para>
    /// Code de production réellement exécuté : <see cref="OpticDbContext"/>,
    /// <see cref="EfTransactionRunner"/>, <see cref="PersistenceErrorMapper"/>,
    /// <c>SupplierRepository.ExistsFreshAsync</c>, et le chemin EF <c>DbSet.Add</c> +
    /// <c>SaveChangesAsync</c> du modèle de production.
    /// </para>
    ///
    /// <para>
    /// LIMITE EXPLICITE : la table <c>"Suppliers"</c> est créée À LA MAIN par le harness, et la
    /// contrainte d'unicité sur <c>"Name"</c> est un INSTRUMENT DE MESURE qui n'existe pas dans le
    /// modèle MMV. Aucun schéma de production n'est revendiqué, aucune migration n'est produite :
    /// la portabilité du schéma reste entièrement à faire en P4-5.
    /// </para>
    /// </summary>
    [SkippableFact]
    public async Task B07_change_tracker_and_exists_fresh_after_failed_save_changes()
    {
        Skip.IfNot(SpikeEnvironment.IsConfigured(Provider), SpikeEnvironment.SkipReason(Provider));

        await using var database = await SpikeDatabase.CreateAsync(Provider, "e21b07");
        SpikeLog.Section(Experiment, Name,
            "B0.7 — ChangeTracker + ExistsFreshAsync apres SaveChanges echoue (chemin CreateProduct/UpdateProduct)");

        // Table du HARNESS, alignée sur le mapping EF de Supplier. Instrument de mesure, pas un schéma.
        await ExecuteOutsideTransactionAsync(database,
            "CREATE TABLE \"Suppliers\" (" +
            "\"SupplierId\" bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT \"PK_Suppliers\" PRIMARY KEY, " +
            "\"Name\" character varying(200) NOT NULL CONSTRAINT ux_harness_supplier_name UNIQUE, " +
            "\"ContactEmail\" character varying(254), " +
            "\"Phone\" character varying(20), " +
            "\"Address\" character varying(500), " +
            "\"ReferenceCode\" character varying(50));");

        // Identifiant semé VOLONTAIREMENT hors de portée immédiate de la séquence d'identité : sans
        // cela, l'INSERT d'EF entrerait en collision sur la CLÉ PRIMAIRE et l'on mesurerait un
        // accident de harness au lieu de la contrainte d'unicité visée.
        const long SeededSupplierId = 100_000L;

        await ExecuteOutsideTransactionAsync(database,
            $"INSERT INTO \"Suppliers\" (\"SupplierId\", \"Name\") VALUES ({SeededSupplierId}, 'FOURNISSEUR-EXISTANT');");

        var recorder = new CommandRecorder();
        await using var context = CreateProductionContext(database, recorder);

        var runner = new EfTransactionRunner(context);              // *** PRODUCTION ***
        var supplierRepository = new SupplierRepository(context);   // *** PRODUCTION ***

        var duplicate = new Supplier { Name = "FOURNISSEUR-EXISTANT" };

        recorder.Start("callback");

        var thrown = await CaptureAsync(() => runner.RunAsync(async ct =>
        {
            // Forme du use case : lecture fraîche DANS la transaction (production).
            var exists = await supplierRepository.ExistsFreshAsync(SeededSupplierId, ct);
            Assert.True(exists);

            // Puis une écriture qui échoue réellement côté serveur.
            context.Suppliers.Add(duplicate);
            await context.SaveChangesAsync(ct);
        }, CancellationToken.None));

        recorder.Stop();

        // --- Chaîne complète EF -> mapper --------------------------------------------------------
        Assert.NotNull(thrown);
        var shape = ExceptionShape.Capture(thrown!);
        SpikeLog.Write(Experiment, Name, $"B0.7 exception sortie du runner | {shape.ToEvidenceLine()}");

        var mapped = Assert.IsType<PersistenceException>(thrown);
        Assert.Equal(PersistenceErrorCategory.UniqueConstraint, mapped.Category);

        var hasDbUpdate = shape.Frames.Any(f => typeof(DbUpdateException).IsAssignableFrom(f.ClrType));
        SpikeLog.Write(Experiment, Name,
            $"B0.7 mapping via SaveChangesAsync | Category={mapped.Category} | SqlState={shape.SqlState} " +
            $"| DbUpdateException presente={(hasDbUpdate ? "OUI" : "NON")}");

        // --- NIVEAU B : état du ChangeTracker APRÈS le rollback ----------------------------------
        var stateAfterRollback = context.Entry(duplicate).State;
        var pendingEntries = context.ChangeTracker.Entries()
            .Count(e => e.State is EntityState.Added or EntityState.Modified or EntityState.Deleted);

        SpikeLog.Write(Experiment, Name,
            $"B0.7 ChangeTracker apres rollback | Entry(duplicate).State={stateAfterRollback} " +
            $"| entrees en attente={pendingEntries} " +
            $"| CurrentTransaction={(context.Database.CurrentTransaction is null ? "null" : "PRESENTE")}");

        Assert.Null(context.Database.CurrentTransaction);

        // --- Le catch de production : ExistsFreshAsync sur le MÊME contexte ----------------------
        recorder.Start("catch");
        var stillExists = await supplierRepository.ExistsFreshAsync(SeededSupplierId, CancellationToken.None);
        recorder.Stop();

        Assert.True(stillExists);

        var catchCommands = recorder.Describe("catch");
        var catchWrites = recorder.WriteCommands("catch");

        SpikeLog.Write(Experiment, Name,
            $"B0.7 ExistsFreshAsync APRES rollback | executee=OUI (aucun 25P02) | resultat={stillExists} " +
            $"| commandes emises={catchCommands} | commandes d'ECRITURE={catchWrites.Count}");

        // Le point critique : la requête du catch ne doit RIEN réécrire, malgré une entité Added.
        Assert.Empty(catchWrites);

        // Et le résultat doit venir de la BASE : l'entité en doublon ne doit pas avoir été persistée.
        var persistedDuplicates = await CountSuppliersNamedAsync(database, "FOURNISSEUR-EXISTANT");
        Assert.Equal(1L, persistedDuplicates);
        SpikeLog.Write(Experiment, Name,
            $"B0.7 donnees apres rollback | lignes 'FOURNISSEUR-EXISTANT' = {persistedDuplicates} " +
            "(la ligne semee, aucune ecriture partielle).");
    }

    // ==================================================================================
    // Outillage LOCAL au harness
    // ==================================================================================

    /// <summary>
    /// VRAI <see cref="OpticDbContext"/> de production sur Npgsql. <c>EnsureCreated</c> et
    /// <c>Migrate</c> ne sont JAMAIS appelés : le modèle n'est pas matérialisé en schéma.
    /// L'intercepteur est une option du HARNESS, jamais de la production.
    /// </summary>
    private static OpticDbContext CreateProductionContext(SpikeDatabase database, CommandRecorder? recorder)
    {
        var builder = new DbContextOptionsBuilder<OpticDbContext>().UseNpgsql(database.ConnectionString);

        if (recorder is not null)
        {
            builder.AddInterceptors(recorder);
        }

        return new OpticDbContext(builder.Options);
    }

    private static async Task ExecuteOutsideTransactionAsync(SpikeDatabase database, string sql)
    {
        await using var connection = await database.OpenRawAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        await command.ExecuteNonQueryAsync();
    }

    private static async Task ExecuteAsync(DbConnection connection, DbTransaction transaction, string sql)
    {
        await using var command = connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText = sql;
        await command.ExecuteNonQueryAsync();
    }

    /// <summary>Compte depuis une connexion NEUVE : la mesure ne peut pas être polluée par la session du test.</summary>
    private static async Task<long> CountProbeAsync(SpikeDatabase database, string code)
    {
        await using var connection = await database.OpenRawAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = "SELECT count(*) FROM p4_tx_probe WHERE code = @code;";
        var parameter = command.CreateParameter();
        parameter.ParameterName = "code";
        parameter.Value = code;
        command.Parameters.Add(parameter);
        return Convert.ToInt64(await command.ExecuteScalarAsync());
    }

    private static async Task<long> CountSuppliersNamedAsync(SpikeDatabase database, string name)
    {
        await using var connection = await database.OpenRawAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = "SELECT count(*) FROM \"Suppliers\" WHERE \"Name\" = @name;";
        var parameter = command.CreateParameter();
        parameter.ParameterName = "name";
        parameter.Value = name;
        command.Parameters.Add(parameter);
        return Convert.ToInt64(await command.ExecuteScalarAsync());
    }

    /// <summary>
    /// Lecture scalaire TOLÉRANTE : si la session refuse la commande (transaction avortée, 25P02),
    /// on renvoie <c>null</c> plutôt que de faire échouer la mesure. Le refus EST une observation.
    /// </summary>
    private static async Task<long?> CaptureScalarAsync(OpticDbContext context, string sql)
    {
        try
        {
            return await context.Database.SqlQueryRaw<long>(sql).SingleAsync();
        }
        catch
        {
            return null;
        }
    }

    private static async Task<Exception?> CaptureAsync(Func<Task> action)
    {
        try
        {
            await action();
            return null;
        }
        catch (Exception exception)
        {
            return exception;
        }
    }
}

/// <summary>
/// Intercepteur de MESURE, propre au harness (B0.4). Il n'enregistre QUE le VERBE SQL (premier
/// mot-clé), l'ordre d'exécution et le succès/échec : jamais un paramètre, jamais une valeur,
/// jamais une chaîne de connexion, jamais un message d'exception.
///
/// <para>
/// LIMITE : <c>BEGIN</c>, <c>COMMIT</c> et <c>ROLLBACK</c> transitent par l'API ADO.NET de
/// transaction (<c>DbTransaction</c>), pas par <c>DbCommand</c> ; un
/// <see cref="DbCommandInterceptor"/> ne peut donc pas les observer. Cette limite est assumée et
/// consignée : la preuve du rollback vient des DONNÉES, pas de cet intercepteur.
/// </para>
/// </summary>
internal sealed class CommandRecorder : DbCommandInterceptor
{
    private readonly object _gate = new();
    private readonly List<Entry> _entries = new();

    private string? _phase;

    public void Start(string phase)
    {
        lock (_gate)
        {
            _phase = phase;
        }
    }

    public void Stop()
    {
        lock (_gate)
        {
            _phase = null;
        }
    }

    public IReadOnlyList<string> CommandsAfterFirstFailure(string phase)
    {
        lock (_gate)
        {
            var phased = _entries.Where(e => e.Phase == phase).ToList();
            var failureIndex = phased.FindIndex(e => e.Failed);
            return failureIndex < 0
                ? Array.Empty<string>()
                : phased.Skip(failureIndex + 1).Select(e => e.Verb).ToList();
        }
    }

    public IReadOnlyList<string> WriteCommands(string phase)
    {
        lock (_gate)
        {
            return _entries
                .Where(e => e.Phase == phase)
                .Select(e => e.Verb)
                .Where(verb => verb is "INSERT" or "UPDATE" or "DELETE" or "MERGE")
                .ToList();
        }
    }

    public string Describe(string phase)
    {
        lock (_gate)
        {
            var phased = _entries
                .Where(e => e.Phase == phase)
                .Select((e, index) => $"{index + 1}.{e.Verb}{(e.Failed ? "(ECHEC)" : "(OK)")}")
                .ToList();

            return phased.Count == 0 ? "(aucune)" : string.Join(" -> ", phased);
        }
    }

    public override InterceptionResult<int> NonQueryExecuting(
        DbCommand command, CommandEventData eventData, InterceptionResult<int> result)
    {
        Record(command);
        return result;
    }

    public override ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(
        DbCommand command, CommandEventData eventData, InterceptionResult<int> result,
        CancellationToken cancellationToken = default)
    {
        Record(command);
        return ValueTask.FromResult(result);
    }

    public override InterceptionResult<DbDataReader> ReaderExecuting(
        DbCommand command, CommandEventData eventData, InterceptionResult<DbDataReader> result)
    {
        Record(command);
        return result;
    }

    public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(
        DbCommand command, CommandEventData eventData, InterceptionResult<DbDataReader> result,
        CancellationToken cancellationToken = default)
    {
        Record(command);
        return ValueTask.FromResult(result);
    }

    public override InterceptionResult<object> ScalarExecuting(
        DbCommand command, CommandEventData eventData, InterceptionResult<object> result)
    {
        Record(command);
        return result;
    }

    public override ValueTask<InterceptionResult<object>> ScalarExecutingAsync(
        DbCommand command, CommandEventData eventData, InterceptionResult<object> result,
        CancellationToken cancellationToken = default)
    {
        Record(command);
        return ValueTask.FromResult(result);
    }

    public override void CommandFailed(DbCommand command, CommandErrorEventData eventData)
        => MarkLastFailed();

    public override Task CommandFailedAsync(
        DbCommand command, CommandErrorEventData eventData, CancellationToken cancellationToken = default)
    {
        MarkLastFailed();
        return Task.CompletedTask;
    }

    private void Record(DbCommand command)
    {
        lock (_gate)
        {
            if (_phase is null)
            {
                return;
            }

            _entries.Add(new Entry(_phase, Verb(command.CommandText), false));
        }
    }

    private void MarkLastFailed()
    {
        lock (_gate)
        {
            if (_phase is null || _entries.Count == 0)
            {
                return;
            }

            _entries[^1] = _entries[^1] with { Failed = true };
        }
    }

    /// <summary>Premier mot-clé SQL uniquement — jamais le texte complet, jamais un paramètre.</summary>
    private static string Verb(string? commandText)
    {
        if (string.IsNullOrWhiteSpace(commandText))
        {
            return "(vide)";
        }

        var tokens = commandText.Split(
            new[] { ' ', '\t', '\r', '\n', '(', ';' }, StringSplitOptions.RemoveEmptyEntries);

        if (tokens.Length == 0)
        {
            return "(vide)";
        }

        var upper = tokens[0].ToUpperInvariant();
        return upper is "SELECT" or "INSERT" or "UPDATE" or "DELETE" or "MERGE"
            or "CREATE" or "DROP" or "ALTER" or "SET" or "BEGIN" or "COMMIT" or "ROLLBACK"
            ? upper
            : "(autre)";
    }

    private sealed record Entry(string Phase, string Verb, bool Failed);
}
